RandomBugle/Controllers/PanelController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RandomBugle.ViewModels;
using RandomBugleDB.Models;
using RandomBugleDB.Models.FileManager;
using RandomBugleDB.Models.Repository;
using System.Threading.Tasks;

namespace RandomBugle.Controllers
{
    [Authorize (Roles ="Admin")]
    public class PanelController : Controller
    {
        private IRepository _repo;
        private IFileManager _filemanager;

        public PanelController(IRepository repo,IFileManager fileManager)
        {
            _repo = repo;
            _filemanager = fileManager;
        }
        public IActionResult Index()
        {
            var posts = _repo.GetAllPosts();
            return View(posts);
        }


        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return View(new PostViewModel());
            }
            else
            {
                var post = _repo.GetPost((int)id);
                return View(new PostViewModel
                {
                    Id = post.Id,
                    Title = post.Title,
                    Body = post.Title,
                    CurrentImage = post.Image,
                    Description =post.Description,
                    Category =post.Category,
                    Tags = post.Tags
                });
            }

        }

        [HttpPost]
        public async Task<IActionResult> Edit(PostViewModel vm)
        {
            var post = new Post
            {
                Id = vm.Id,
                Title = vm.Title,
                Body = vm.Body,
                Description = vm.Description,
                Category = vm.Category,
                Tags = vm.Tags,
                //Image = await _filemanager.SaveImage(vm.Image)

            };
            if (vm.Image == null)
                post.Image = vm.CurrentImage;
            else
                if (!string.IsNullOrEmpty(vm.CurrentImage))
                _filemanager.RemoveImage(vm.CurrentImage);

                post.Image = await _filemanager.SaveImage(vm.Image);

            if (post.Id > 0)
                _repo.UpdatePost(post);
            else
                _repo.AddPost(post);

            if (await _repo.SaveChangesAsync())
                return RedirectToAction("Index");
            else
                return View(post);
        }


        [HttpGet]
        public async Task<IActionResult> Remove(int id)
        {
            _repo.RemovePost(id);
            await _repo.SaveChangesAsync();
            return RedirectToAction("Index");


        }
    }
}

RandomBugle/Views/Panel/Edit.cshtml
@model RandomBugle.ViewModels.PostViewModel
@{

}
<link rel="stylesheet" href="~/lib/Trumbowyg-main/dist/ui/trumbowyg.min.css">
<div>
    <form asp-controller="Panel" asp-action="Edit" method="post" enctype="multipart/form-data">
        <input asp-for="Id" type="hidden" />
        <div>
            <lable>title</lable>
            <input asp-for="Title"/>
        </div> 
        <div>
            <lable>Description</lable>
            <input asp-for="Description"/>
        </div> 
        <div>
            <lable>Tags</lable>
            <input asp-for="Tags"/>
        </div> 
        <div>
            <lable>Category</lable>
          
            <select asp-for="Category">
               <option value="Travel">Travel</option>
               <option value="Programming">Programming</option>
               <option value="Photoraphy">Photoraphy</option>

            </select>
        </div> 
         <div>
            <lable>Body</lable>
            <textarea id="editor"  asp-for="Body"></textarea>
        </div> 
         <div>
            <lable>Image</lable>
            <input asp-for="Image"/>
             <input asp-for="CurrentImage" type="hidden"/>
        </div>
        <input type="submit" value="Submit">
    </form>
    
</div>

@section scripts{
    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
   <script src="~/lib/Trumbowyg-main/dist/trumbowyg.min.js"></script>
   <script>
       $('#editor').trumbowyg();
       //.-- class
       // # - id
       // nav-  html element
   </script>
}

RandomBugle/Views/Panel/Index.cshtml
@model IEnumerable<RandomBugleDB.Models.Post>
@{

}
<h1>Admin Panel</h1>
<a asp-controller="Panel" asp-action="Edit" >
 Add new Post
</a>
<div>
    <ul>
        @foreach(var post in Model)
        {
            <li>
              
                    @post.Title
              
                <a asp-controller="Panel" asp-action="Edit" asp-route-id="@post.Id" >
                   Edit 
                </a>
                <a asp-controller="Panel" asp-action="Remove" asp-route-id="@post.Id" >
                   Remove 
                </a>
            </li>
        }
    </ul>.
</div>